language: node_js
node_js:
  - 'lts/*'
cache: yarn
before_install:
  - yarn global add codecov
script:
  - yarn build
  - yarn test
  - if [[ $TRAVIS_EVENT_TYPE != 'pull_request' ||  $TRAVIS_PULL_REQUEST_SLUG != $TRAVIS_REPO_SLUG ]];
    then
    yarn test:vr || true;
    fi
after_success:
  - codecov
